Add --version command line option
fritzing/fritzing-app pull request #3475
Opened 2019-05-16 19:20 UTC by cjmayo

Split from #3242.

Copyright and mention of Friends-of-Fritzing e.V. need review.

2019-05-28 14:41 UTC, madpipeline approved these changes

2019-05-28 14:41 UTC, ovidiub13 commented on src/main.cpp
> +                "Copyright (C) 2016 ???.\n"
You can add `2019`. We plan several releases this year.

2019-05-28 14:41 UTC, ovidiub13 commented on src/main.cpp
> +                "Maintained by the Friends-of-Fritzing e.V.\n";
@KjellMorgenstern is this right?

2019-05-28 14:41 UTC, ovidiub13 commented on src/main.cpp
> +        }
Can you format the indentation?

2019-05-28 14:57 UTC, madpipeline requested changes

2019-05-28 14:57 UTC, ovidiub13 commented on src/main.cpp
> +                "Maintained by the Friends-of-Fritzing e.V.\n";
After some discussion with @KjellMorgenstern, we've think it's best for now to not have the © in the `--version` message due to the complicated legal situation of Fritzing right now.
In order not to hold this PR back: can you strip this message to just the version print? We'll revisit the © part later.

2019-05-31 18:39 UTC, cjmayo commented
Stripped back to version number only.
Replaced all tabs with spaces to improve the indentation.

2019-06-06 07:26 UTC, KjellMorgenstern approved these changes

2019-06-06 07:27 UTC, merged