Support using system QuaZIP on Qt5 and output build messages for system libgit2 and QuaZIP
fritzing/fritzing-app pull request #3478
Opened 2019-05-17 18:26 UTC by cjmayo

* Currently Qt5 builds can't use system QuaZIP because it is using quazip5 locations.
* Add build-time messages to inform about the use of system libraries
* Don't output three copies of the build-time messages

A bit more info in the commit messages.

This is an updated version of the work in #3254 and a copy of #3468.

Happy to squash commits in this PR or split into separate PRs if preferred.

2019-05-28 14:36 UTC, madpipeline approved these changes
Looks ok to me. @KjellMorgenstern you ok if we merge this?

2019-05-28 14:43 UTC, ovidiub13 commented
@cjmayo on what system and with what compiler are you building this?

2019-05-30 18:56 UTC, cjmayo commented
I'm using Gentoo Linux with GCC 8.3.0. QuaZIP 0.7.6.

2019-07-13 14:09 UTC, KjellMorgenstern commented
I see two issues with this PR.
1. Linking with QuaZIP works fine, why risk breaking things?
2. Linking against a system QuaZIP is not tested in CI.

I think the preferred way to fix this should be to remove the quazip code from Fritzing entirely, and adapt the CI accordingly. This way we would only have to maintain the dependency, as with every other library, not the library itself. Opinions?

2019-07-13 14:14 UTC, KjellMorgenstern requested changes
I think it is better to remove the copy of quazip from Fritzing, and properly link against the library instead.

2019-07-16 18:40 UTC, cjmayo commented
Removing bundled QuaZIP sounds good to me.

2019-10-19 18:59 UTC, cjmayo commented
Updated onto latest develop. I don't use or know much about static linking but hopefully this could be the basis for still allowing dynamic linking to a system library and modified for static linking to a Fritizing copy.

2019-10-20 07:57 UTC, merged